### ISSUE TITLE
[JENKINS-64599]  yamlMergeStrategy  merge() doesn't inherit volume mounts from parent pod template

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/kubernetes-plugin#2417]
<p>Agent declaration with yaml template: </p>

<pre>
inheritFrom <span class="code-quote">'k8s-dind'</span>
yamlMergeStrategy merge()
yaml """
  apiVersion: v1
  kind: Pod
  spec:
   containers:
   - name: apaasdevops
     image: <repo_URL>/apaas/apaas-devops:1.20
     workingDir: /home/jenkins
     command: [<span class="code-quote">'cat'</span>]
     tty: <span class="code-keyword">true</span>
"""
</pre>
<p>Agent declaration with container template: </p>

<pre>
inheritFrom <span class="code-quote">'k8s-dind'</span>
containerTemplate {
   name <span class="code-quote">'apaasdevops'</span>
   image <span class="code-quote">'<repo_name>/apaas/apaas-devops:1.20'</span>
   workingDir <span class="code-quote">'/home/jenkins'</span>
   ttyEnabled <span class="code-keyword">true</span>
   command <span class="code-quote">'cat'</span>
   args ''
}
</pre>
<p> </p>

<p>Container templates inherit the env and volume mounts from parent pod as shown below</p>

```
spec:
  containers:
  - command:
    - "cat"
    env:
    - name: "DOCKER_HOST"
      value: "tcp://<IP_ADDRESS>"
    image: "*****/apaas/apaas-devops:1.20"
    imagePullPolicy: "IfNotPresent"
    name: "apaasdevops"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: "/var/lib/docker"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  - args:
    - "-disableHttpsCertValidation"
    - "********"
```
<p>But yaml template is not not inheriting volume mounts and env even though yamlMergeStrategy merge() is used while defining agent</p>

```
spec:
  containers:
  - command:
    - "cat"
    image: "*****/apaas/apaas-devops:1.20"
    name: "apaasdevops"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  - args:
    - "-disableHttpsCertValidation"
    - "********"
```
<p> kubernetes plugin used is 1.25.4 version</p>

<p>Below volume mount is configured in parent pod 'k8s-dind' <font color="#172b4d">which is not getting inherited in yaml template but gets inherited in container template</font></p>

<pre>
- mountPath: <span class="code-quote">"/<span class="code-keyword">var</span>/lib/docker"</span> 
  name: <span class="code-quote">"volume-0"</span> 
  readOnly: <span class="code-keyword">false</span>
</pre>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=appu">appu</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-64599" target="_blank"> yamlMergeStrategy  merge() doesn't inherit volume mounts from parent pod template</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: kubernetes-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 2
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Agent declaration with yaml template: </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">inheritFrom <span class="code-quote">'k8s-dind'</span>
yamlMergeStrategy merge()
yaml """
  apiVersion: v1
  kind: Pod
  spec:
   containers:
   - name: apaasdevops
     image: &lt;repo_URL&gt;/apaas/apaas-devops:1.20
     workingDir: /home/jenkins
     command: [<span class="code-quote">'cat'</span>]
     tty: <span class="code-keyword">true</span>
"""
</pre>
</div></div>
<p>Agent declaration with container template: </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">inheritFrom <span class="code-quote">'k8s-dind'</span>
containerTemplate {
   name <span class="code-quote">'apaasdevops'</span>
   image <span class="code-quote">'&lt;repo_name&gt;/apaas/apaas-devops:1.20'</span>
   workingDir <span class="code-quote">'/home/jenkins'</span>
   ttyEnabled <span class="code-keyword">true</span>
   command <span class="code-quote">'cat'</span>
   args ''
}
</pre>
</div></div>
<p> </p>

<p>Container templates inherit the env and volume mounts from parent pod as shown below</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>spec:
  containers:
  - command:
    - "cat"
    env:
    - name: "DOCKER_HOST"
      value: "tcp://&lt;IP_ADDRESS&gt;"
    image: "*****/apaas/apaas-devops:1.20"
    imagePullPolicy: "IfNotPresent"
    name: "apaasdevops"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: "/var/lib/docker"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  - args:
    - "-disableHttpsCertValidation"
    - "********"</pre>
</div></div>
<p>But yaml template is not not inheriting volume mounts and env even though yamlMergeStrategy merge() is used while defining agent</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>spec:
  containers:
  - command:
    - "cat"
    image: "*****/apaas/apaas-devops:1.20"
    name: "apaasdevops"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  - args:
    - "-disableHttpsCertValidation"
    - "********"</pre>
</div></div>
<p> kubernetes plugin used is 1.25.4 version</p>

<p>Below volume mount is configured in parent pod 'k8s-dind' <font color="#172b4d">which is not getting inherited in yaml template but gets inherited in container template</font></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">- mountPath: <span class="code-quote">"/<span class="code-keyword">var</span>/lib/docker"</span> 
  name: <span class="code-quote">"volume-0"</span> 
  readOnly: <span class="code-keyword">false</span>
</pre>
</div></div>
<p> </p>

<p> </p></pre>
</details>
</details>
