### ISSUE TITLE
Allow to specify 'Pull Image Secret' to use private docker registries

### ISSUE THREAD

**Issue by ichekrygin** [jenkinsci/kubernetes-plugin#32]
Describe here: http://kubernetes.io/v1.0/docs/user-guide/images.html

Example:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
    - name: myregistrykey
```
